### ISSUE TITLE
Cannot signup as a host

### ISSUE THREAD

**Issue by zabawaba99** [yannickcalleiro/gighub#11]
I navigated to the home page http://gighubwebapp.herokuapp.com/. I then clicked on Create Account and then new host. This is what I saw

![screen shot 2015-07-29 at 8 52 40 am](https://cloud.githubusercontent.com/assets/2306786/8957895/7f63e618-35cf-11e5-85fc-412baa472b5f.png)

**Comment by yannickcalleiro** [comment]
Yeah, it works locally but when I deployed it wasn’t working. That’s on my to-do this morning.

**Comment by zabawaba99** [comment]
:+1:
