### ISSUE TITLE
Photo Input Field 

### ISSUE THREAD

**Issue by yannickcalleiro** [yannickcalleiro/gighub#15]
Create photo using Gravatar. Email provided will generate photo.

**Comment by jjcall** [comment]
Only issue here is, no one uses gravatar unless they are a techy

**Comment by yannickcalleiro** [comment]
I decided to do a method to upload a photo. Used Paperclip gem, more information can be found here: https://github.com/thoughtbot/paperclip. Also, added a placeholder image when the user does not have an image.
