### ISSUE TITLE
Sorting Events

### ISSUE THREAD

**Issue by zabawaba99** [yannickcalleiro/gighub#26]
Do you plan on sorting events? I had created three events for different dates and they came back in the order that I created them, not in any particular date order.

![screen shot 2015-07-31 at 2 23 40 pm](https://cloud.githubusercontent.com/assets/2306786/9014408/34cdeabe-3790-11e5-803c-04679d8914d8.png)

This is more of a question, not necessarily an issue.

**Comment by zabawaba99** [comment]
Also, one of the issues was for a date that already past. Not too sure if you'd like to hide those.

**Comment by yannickcalleiro** [comment]
I just added a method to sort by date then name. I'll have to make method to only show events for today and upcoming. I'll probably show past event or event history in a separate tab or page.

**Comment by yannickcalleiro** [comment]
I rewrote the method and added an additional method to filter out older events.
